management:
  server:
    port: 8889

server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          refresh-rate: 15
          # poorly documented, but this allows us to break up configurations into organizations, achieving multi-tenancy
          # for further details, see how we set spring.application.name in example-client
          search-paths: '{application}'
          uri: https://github.com/mightychip/cloud-config-properties.git
