version: "3.8"

services:
  database:
    container_name: database
    image: localhost:5000/cloud-config-demo-database:latest
    ports:
      - "5432:5432"
    networks:
      - example

  cloud-config-server:
    depends_on:
      - database
    container_name: cloud-config-server
    image: localhost:5000/cloud-config-demo-server:latest
    ports:
      - "8888:8888"
    networks:
      - example

  example-client:
    container_name: cloud-config-client
    depends_on:
      - cloud-config-server
      - database
    image: localhost:5000/cloud-config-demo-client:latest
    ports:
      - "8085:8085"
      - "8086:8086"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - example

networks:
  example: